---
title: "Compare copulasso and gcoda fits"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  df_print: paged
---
```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "../")
```

```{r setup2, include=FALSE}
library(magrittr)
library(ggplot2)
set.seed(1)
```

```{r load data, include=FALSE}
load("../data/genera_adj.RData")
physeq <- physeq_genera_adj %>% 
  phyloseq::subset_samples(dataset_name == "MucosalIBD") %>% 
  smar::prune_taxaSamples(flist_taxa = genefilter::kOverA(k = 5, A = 1))
mat_X_count <- smar::otu_table2(physeq)
mat_X_p <- apply(mat_X_count, 2, function(x) x / sum(x))
df_marginals <- CRTmicrobiome:::get_marginals(t(mat_X_p))
rho_original <- CRTmicrobiome:::cor2(t(mat_X_p))
```

# Agenda

* Two different models for p exist, copulasso and gcoda.

* Compare their performance on marginals and spearman correlations

```{r fit copulasso, include=FALSE}
fit_copulasso <- CRTmicrobiome:::copulasso(
  data = t(mat_X_p),
  lambda_list = seq(0.03, 0.5,
                    by = 0.01))
fit_copulasso_optim <- 
  fit_copulasso$fits[[order(fit_copulasso$df_eval$BIC)[1]]]
```

```{r fit gcoda with pseudo count, include=FALSE}
mat_X_p_pseudocount <- apply(mat_X_count + 0.5, 2, function(x) x / sum(x))
fit_gcodaPC <- CRTmicrobiome:::gcoda(
  data = t(mat_X_p_pseudocount),
  lambda_list = seq(0.04, 1.6,
                    by = 0.02))
fit_gcodaPC_optim <- 
  fit_gcodaPC$fits[[order(fit_gcodaPC$df_eval$BIC)[1]]]
```

```{r fit gcoda with pseudo value, include=FALSE}
mat_X_p_pseudoval <- 
  mat_X_p + min(setdiff(mat_X_p, 0)) / 2
fit_gcodaPV <- CRTmicrobiome:::gcoda(
  data = t(mat_X_p_pseudoval),
  lambda_list = seq(0.3, 2.4,
                    by = 0.02))
fit_gcodaPV_optim <- 
  fit_gcodaPV$fits[[order(fit_gcodaPV$df_eval$BIC)[1]]]
```

```{r compare spearman corrs, echo=FALSE, fig.height=12}
R <- 100000

# copulasso
samples_copulasso <- 
  CRTmicrobiome:::rcopulasso(n = R,
                             mean = df_marginals$mu,
                             sd = df_marginals$sigma,
                             pi = df_marginals$pi,
                             sigma = solve(fit_copulasso_optim),
                             norm = TRUE)
rho_copulasso <- CRTmicrobiome:::cor2(samples_copulasso)
p_copulasso <- 
  CRTmicrobiome:::plot_cors(rho_original, 
                            fit_copulasso_optim %>% 
                              solve %>% 
                              CRTmicrobiome:::Rho(),
                            labels = c("original", "fit")) +
  ggtitle("copulasso estimate")
p_copulasso_norm <- 
  CRTmicrobiome:::plot_cors(rho_original, rho_copulasso, 
                            labels = c("original", "fit")) +
  ggtitle("copulasso renormalized empirical")

# gcoda pseudo count
mu_a <- CRTmicrobiome:::mean_logisticMVN(data = t(mat_X_p_pseudocount))
samples_a <- mvtnorm::rmvnorm(n = R, 
                              mean = mu_a, 
                              sigma = solve(fit_gcodaPC_optim))
samples_gcodaPC <- t(apply(samples_a, 1, function(x) exp(x) / sum(exp(x))))
rho_gcodaPC <- cor(samples_gcodaPC, method = "spearman")
samples_gcodaPC_ZI <- 
  CRTmicrobiome:::enforce_ZI(samples_gcodaPC, df_marginals$pi)
rho_gcodaPC_ZI <-  CRTmicrobiome:::cor2(samples_gcodaPC_ZI)
p_gcodaPC <- 
  CRTmicrobiome:::plot_cors(rho_original, rho_gcodaPC, 
                            labels = c("original", "fit")) +
  ggtitle("gcoda with pseudo count")
p_gcodaPC_ZI <- 
  CRTmicrobiome:::plot_cors(rho_original, rho_gcodaPC_ZI, 
                            labels = c("original", "fit")) +
  ggtitle("gcoda with pseudo count, enforced ZI")

# gcoda pseudo value
mu_a <- CRTmicrobiome:::mean_logisticMVN(data = t(mat_X_p_pseudoval))
samples_a <- mvtnorm::rmvnorm(n = R, 
                              mean = mu_a, 
                              sigma = solve(fit_gcodaPV_optim))
samples_gcodaPV <- t(apply(samples_a, 1, function(x) exp(x) / sum(exp(x))))
rho_gcodaPV <- cor(samples_gcodaPV, method = "spearman")
samples_gcodaPV_ZI <- 
  CRTmicrobiome:::enforce_ZI(samples_gcodaPV, df_marginals$pi)
rho_gcodaPV_ZI <-  CRTmicrobiome:::cor2(samples_gcodaPV_ZI)
p_gcodaPV <- 
  CRTmicrobiome:::plot_cors(rho_original, rho_gcodaPV, 
                            labels = c("original", "fit")) +
  ggtitle("gcoda with pseudo count")
p_gcodaPV_ZI <- 
  CRTmicrobiome:::plot_cors(rho_original, rho_gcodaPV_ZI, 
                            labels = c("original", "fit")) +
  ggtitle("gcoda with pseudo count, enforced ZI")
cowplot::plot_grid(p_copulasso, p_copulasso_norm,
                   p_gcodaPC, p_gcodaPC_ZI,
                   p_gcodaPV, p_gcodaPV_ZI,
                   ncol = 2)
```

```{r compare marginals, echo=FALSE, fig.width=16, fig.height=8}
simp_names <- rownames(mat_X_p) %>% 
  stringr::str_replace_all(stringr::fixed("|NA|NA"), "") %>% 
  stringr::str_replace_all(".*\\|f\\_\\_", "f__")
l_p_original <- 
  purrr::map2(seq_len(nrow(mat_X_p)), simp_names,
         function(i, bug) 
           ggplot(data.frame(abd = mat_X_p[i, , drop = TRUE] %>% 
                               CRTmicrobiome:::log_with_zero()),
                  aes(x = abd)) +
           geom_histogram(bins = 30) + 
           ggtitle(bug))
l_p_copulasso <- 
  purrr::map2(seq_len(nrow(mat_X_p)), simp_names,
         function(i, bug) 
           ggplot(data.frame(abd = samples_copulasso[, i, drop = TRUE] %>% 
                               CRTmicrobiome:::log_with_zero()),
                  aes(x = abd)) +
           geom_histogram(bins = 30) + 
           ggtitle(bug))
l_p_gcodaPC <-
  purrr::map2(seq_len(nrow(mat_X_p)), simp_names,
         function(i, bug) 
           ggplot(data.frame(abd = samples_gcodaPC[, i, drop = TRUE]) %>% 
                               CRTmicrobiome:::log_with_zero(),
                  aes(x = abd)) +
           geom_histogram(bins = 30) + 
           ggtitle(bug))
l_p_gcodaPV <-
  purrr::map2(seq_len(nrow(mat_X_p)), simp_names,
              function(i, bug) 
                ggplot(data.frame(abd = samples_gcodaPV[, i, drop = TRUE]) %>% 
                         CRTmicrobiome:::log_with_zero(),
                       aes(x = abd)) +
                geom_histogram(bins = 30) + 
                ggtitle(bug))
dir.create("../results/copulasso_vs_gcoda/", showWarnings = FALSE)
pdf("../results/copulasso_vs_gcoda/marginals.pdf",
    width = 16, height = 5)
for(i in seq_along(l_p_original)) {
  p <- cowplot::plot_grid(
    l_p_original[[i]],
    l_p_copulasso[[i]],
    l_p_gcodaPC[[i]],
    l_p_gcodaPV[[i]],
    nrow = 1
  ) 
  print(p)
}
dev.off()
# visualize some examples here
for(i_bug in c("f__Ruminococcaceae|g__Ruminococcus",
               "f__Micrococcaceae|g__Rothia")) {
  i <- which(simp_names == i_bug)
  cowplot::plot_grid(
    l_p_original[[i]],
    l_p_copulasso[[i]],
    l_p_gcodaPC[[i]],
    l_p_gcodaPV[[i]],
    nrow = 1
  ) %>% 
    print()
}
```

```{r model evaluations, echo=FALSE, fig.width=8, fig.height=12}
fit_copulasso$df_eval %>%
  dplyr::mutate(sparsity = df / ncol(mat_X_p) / (ncol(mat_X_p) - 1) * 2) %>%
  tidyr::gather(key = metric_name, value = metric,
                negLogLik_CV, sparsity, AIC, BIC, EBIC) %>%
  ggplot(aes(x = lambda, y = metric)) +
  geom_point() + geom_line() +
  facet_wrap(.~metric_name, scales = "free_y", ncol = 1) +
  ggtitle("Copula lasso fits")
fit_copulasso$df_eval %>% 
  tidyr::gather(key = metric_name, value = metric,
                negLogLik_CV, AIC, BIC, EBIC) %>% 
  dplyr::group_by(metric_name) %>% 
  dplyr::arrange(metric) %>% 
  dplyr::slice(1) %>% 
  dplyr::ungroup() %>% 
  print()
fit_gcodaPC$df_eval %>%
  dplyr::mutate(sparsity = df / ncol(mat_X_p) / (ncol(mat_X_p) - 1) * 2) %>%
  tidyr::gather(key = metric_name, value = metric,
                negLogLik_CV, sparsity, AIC, BIC, EBIC) %>%
  ggplot(aes(x = lambda, y = metric)) +
  geom_point() + geom_line() +
  facet_wrap(.~metric_name, scales = "free_y", ncol = 1) +
  ggtitle("gcoda fits with pseudo count = 0.5")
fit_gcodaPC$df_eval %>% 
  tidyr::gather(key = metric_name, value = metric,
                negLogLik_CV, AIC, BIC, EBIC) %>% 
  dplyr::group_by(metric_name) %>% 
  dplyr::arrange(metric) %>% 
  dplyr::slice(1) %>% 
  dplyr::ungroup() %>% 
  print()
fit_gcodaPV$df_eval %>%
  dplyr::mutate(sparsity = df / ncol(mat_X_p) / (ncol(mat_X_p) - 1) * 2) %>%
  tidyr::gather(key = metric_name, value = metric,
                negLogLik_CV, sparsity, AIC, BIC, EBIC) %>%
  ggplot(aes(x = lambda, y = metric)) +
  geom_point() + geom_line() +
  facet_wrap(.~metric_name, scales = "free_y", ncol = 1) +
  ggtitle("gcoda fits with pseudo value = min non-zero/2")
fit_gcodaPV$df_eval %>% 
  tidyr::gather(key = metric_name, value = metric,
                negLogLik_CV, AIC, BIC, EBIC) %>% 
  dplyr::group_by(metric_name) %>% 
  dplyr::arrange(metric) %>% 
  dplyr::slice(1) %>% 
  dplyr::ungroup() %>% 
  print()
```